### ISSUE TITLE
Такая проверка всегда будет возвращать true. Как думаете, почему?

### ISSUE THREAD

**Issue by frontgirl** [Agriell/JavaScript#4]
https://github.com/Agriell/JavaScript/blob/ed60a4afc5c1edc35dbd7d47af64abd03a56a56a/game.js#L73

**Comment by Agriell** [comment]
Когда я это написал, я подумал что пустой массив это тоже false.
Но ошибка устранена по ходу устранения предыдущего замечания про Math.max()
